package FlightReservationApp;


/**
* FlightReservationApp/FlightReservation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightReservation.idl
* Saturday, December 3, 2016 4:38:00 AM EST
*/

public interface FlightReservation extends FlightReservationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlightReservation
