package FlightReservationApp;

/**
* FlightReservationApp/FlightReservationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightReservation.idl
* Saturday, December 3, 2016 4:38:00 AM EST
*/

public final class FlightReservationHolder implements org.omg.CORBA.portable.Streamable
{
  public FlightReservationApp.FlightReservation value = null;

  public FlightReservationHolder ()
  {
  }

  public FlightReservationHolder (FlightReservationApp.FlightReservation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FlightReservationApp.FlightReservationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FlightReservationApp.FlightReservationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FlightReservationApp.FlightReservationHelper.type ();
  }

}
