package FlightReservationApp;


/**
* FlightReservationApp/FlightReservation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightReservation.idl
* Sunday, December 4, 2016 1:33:22 AM EST
*/

public interface FlightReservation extends FlightReservationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlightReservation
