package DFRSApp;


/**
* DFRSApp/DFRSHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/valeriehayot/Documents/DistributedSystems/4.Project/A2-fix/COMP6321_A2/Server/src/DFRS.idl
* Sunday, November 13, 2016 3:23:52 PM EST
*/

abstract public class DFRSHelper
{
  private static String  _id = "IDL:DFRSApp/DFRS:1.0";

  public static void insert (org.omg.CORBA.Any a, DFRSApp.DFRS that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DFRSApp.DFRS extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DFRSApp.DFRSHelper.id (), "DFRS");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DFRSApp.DFRS read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DFRSStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DFRSApp.DFRS value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DFRSApp.DFRS narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DFRSApp.DFRS)
      return (DFRSApp.DFRS)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DFRSApp._DFRSStub stub = new DFRSApp._DFRSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DFRSApp.DFRS unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DFRSApp.DFRS)
      return (DFRSApp.DFRS)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DFRSApp._DFRSStub stub = new DFRSApp._DFRSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
