package DFRSApp;


/**
* DFRSApp/DFRSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/valeriehayot/Documents/DistributedSystems/4.Project/A2-fix/COMP6321_A2/Server/src/DFRS.idl
* Sunday, November 13, 2016 3:23:52 PM EST
*/

public abstract class DFRSPOA extends org.omg.PortableServer.Servant
 implements DFRSApp.DFRSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("bookFlight", new java.lang.Integer (0));
    _methods.put ("getBookedFlightCount", new java.lang.Integer (1));
    _methods.put ("editFlightRecord", new java.lang.Integer (2));
    _methods.put ("transferReservation", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DFRSApp/DFRS/bookFlight
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phone = in.read_string ();
         String destination = in.read_string ();
         String date = in.read_string ();
         String flightClass = in.read_string ();
         String $result = null;
         $result = this.bookFlight (firstName, lastName, address, phone, destination, date, flightClass);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DFRSApp/DFRS/getBookedFlightCount
       {
         String recordType = in.read_string ();
         String $result = null;
         $result = this.getBookedFlightCount (recordType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DFRSApp/DFRS/editFlightRecord
       {
         String recordID = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         String $result = null;
         $result = this.editFlightRecord (recordID, fieldName, newValue);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DFRSApp/DFRS/transferReservation
       {
         String passengerID = in.read_string ();
         String currentCity = in.read_string ();
         String otherCity = in.read_string ();
         String $result = null;
         $result = this.transferReservation (passengerID, currentCity, otherCity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DFRSApp/DFRS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DFRS _this() 
  {
    return DFRSHelper.narrow(
    super._this_object());
  }

  public DFRS _this(org.omg.CORBA.ORB orb) 
  {
    return DFRSHelper.narrow(
    super._this_object(orb));
  }


} // class DFRSPOA
