package DFRSApp;


/**
* DFRSApp/DFRS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/valeriehayot/Documents/DistributedSystems/4.Project/A2-fix/COMP6321_A2/Server/src/DFRS.idl
* Sunday, November 13, 2016 3:23:52 PM EST
*/

public interface DFRS extends DFRSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DFRS
