package DFRSApp;


/**
* DFRSApp/DFRSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/valeriehayot/Documents/DistributedSystems/4.Project/A2-fix/COMP6321_A2/Server/src/DFRS.idl
* Sunday, November 13, 2016 3:23:52 PM EST
*/

public interface DFRSOperations 
{
  String bookFlight (String firstName, String lastName, String address, String phone, String destination, String date, String flightClass);
  String getBookedFlightCount (String recordType);
  String editFlightRecord (String recordID, String fieldName, String newValue);
  String transferReservation (String passengerID, String currentCity, String otherCity);
} // interface DFRSOperations
