
package com.vhs.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ManagerServerImplServiceWST", targetNamespace = "http://server.vhs.com/", wsdlLocation = "http://localhost:8082/wst?wsdl")
public class ManagerServerImplServiceWST
    extends Service
{

    private final static URL MANAGERSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MANAGERSERVERIMPLSERVICE_EXCEPTION;
    private final static QName MANAGERSERVERIMPLSERVICE_QNAME = new QName("http://server.vhs.com/", "ManagerServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/wst?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANAGERSERVERIMPLSERVICE_WSDL_LOCATION = url;
        MANAGERSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public ManagerServerImplServiceWST() {
        super(__getWsdlLocation(), MANAGERSERVERIMPLSERVICE_QNAME);
    }

    public ManagerServerImplServiceWST(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANAGERSERVERIMPLSERVICE_QNAME, features);
    }

    public ManagerServerImplServiceWST(URL wsdlLocation) {
        super(wsdlLocation, MANAGERSERVERIMPLSERVICE_QNAME);
    }

    public ManagerServerImplServiceWST(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANAGERSERVERIMPLSERVICE_QNAME, features);
    }

    public ManagerServerImplServiceWST(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManagerServerImplServiceWST(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ManagerServer
     */
    @WebEndpoint(name = "ManagerServerImplPort")
    public ManagerServer getManagerServerImplPort() {
        return super.getPort(new QName("http://server.vhs.com/", "ManagerServerImplPort"), ManagerServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManagerServer
     */
    @WebEndpoint(name = "ManagerServerImplPort")
    public ManagerServer getManagerServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.vhs.com/", "ManagerServerImplPort"), ManagerServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANAGERSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw MANAGERSERVERIMPLSERVICE_EXCEPTION;
        }
        return MANAGERSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
