package FlightReservationApp;


/**
* FlightReservationApp/FlightReservation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightReservation.idl
* Sunday, November 6, 2016 11:45:09 PM EST
*/

public interface FlightReservation extends FlightReservationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlightReservation
